package com.example.mydegree.Room;

import java.lang.reflect.Array;
import java.util.ArrayList;

public class InsertData {

    public static ArrayList<Course> getCourses(){
        ArrayList<Course> courses = new ArrayList<>();
        courses.add(0, new Course("3979","Information Systems",null,0,0,0,false,false,false,null,null));
        courses.add(1,new Course("3964", "Information Systems (Co-op) (Hons)", null,0,0,0,false,false,false,null,null));
        courses.add(2,new Course("3584", "Commerce / Information Systems", null, 0,0,0,false,false,false,null,null));
        courses.add(new Course("INFS1602","Digital Transformation in Business","This is a foundational (Level 1) Information Systems (IS) course that introduces students to the use of IS in business and society. As an overarching theme, INFS1602 examines the issues and management of IS in relation to human behaviour and its consequences. Through this course, students will learn to appreciate existing and emerging technologies affecting businesses, business relationships and their products and services. In taking this course, students will be provided with tasks and assignments that will aid in refining their professional business skills and the ability to evaluate the value of technology to businesses. This includes communication and group work skills, time management and research skills.\n" +
                "\n" +
                "The topics that are covered in INFS1602 include understanding the role of Information Systems and IS Professionals in Global Business, the relationship between Information Systems, Organisations, and Strategy, the dominant Business Models enabled by the Internet and Web 2.0 technology. The course will also explore contemporary technologyenabled phenomena that are disruptive to the current business landscape. The course also touches on popular enterprise-level information systems such as Enterprise Systems, Supply Chain and Customer Relationship Management Systems and the emergence of business intelligence in supporting organisation decision making. The course also involves discussion of the considerations behind the acquisition and building of IS and the issues common to the management of IS projects. Lastly, the course addresses the need to secure the IS and the potential ethical and social issues faced by businesses in relation to their use of IS.",1,6,4.5, true,true,true, null, "Face-to-face"));
        courses.add(new Course("INFS1603", "Introduction to Business Databases","This is a foundational (Level 1) Information Systems (IS) course that introduces students to the concepts, techniques, and technologies relevant for creating and managing business databases. It will explain the major components of IS, which are critical to capturing, transmitting, storing, retrieving, manipulating and displaying information used in business processes. Through this course, students will be exposed to the fundamental knowledge of business databases, which are foundational for many advanced courses. Students will be given tasks and assignments to help them acquire the ability to create and manage business databases.",1,6,4,true,true,false,null,"Face-to-face"));
        courses.add(new Course("INFS1609","Fundamentals of Business Programming", "This is a foundational (Level 1) Information Systems (IS) course that introduces students to application programming. The course provides a first step towards learning the principles of object-oriented programming through the Java programming language. Programming refers to the development of software, which is also called a program. Essentially, software contains the instructions that tell computerised devices what to do. In lectures, students will be introduced to the theoretical component of the course, learning fundamental programming concepts. During weekly workshop tutorials, students will engage in the practical component of the course, learning how to write code using the NetBeans Integrated Development Environment.\n" +
                "\n" +
                "The topics that are covered in INFS1609 introduce students to the fundamentals of Java programming. This begins with an overview of data types and methods before introducing students to small problem-solving exercises that require the use of conditional statements, loops and arrays (including multi-dimensional arrays and array lists). Students are then introduced to the topics of modular programming, testing and debugging (using JUNIT). Finally, having gained a general understanding of these concepts, students further explore the principles of object-oriented programming, including objects, classes, abstraction, polymorphism, inheritance and encapsulation.",1,6,4,true,false,true,"Not in INFS2609/COMP1400","Face-to-face"));
        courses.add(new Course("ACCT1501","Accounting and Financial Management 1A","The compulsory core accounting unit will have a preparer perspective. It will provide an introduction to basic concepts in accounting and their application for decision making by a wide range of potential users (e.g., shareholders, investment analysts, lenders, managers etc). This unit should benefit students who wish to specialise in accounting, and will also be of value to students whose primary interest lies elsewhere in the field of business.\n" +
                "\n" +
                "On completion, students should have a clear understanding of the accounting process and the language of accounting to enable communication with an accounting professional, understand the relevance of accounting information for informed decision making by a wide range of potential users, and have the ability to analyse and interpret accounting information. Topics covered will include the accounting equation, general purpose financial reports, cash and accrual accounting, adjustments, internal control, financial statement analysis, and interpreting and preparing information for managers to use in planning, decision making and control.",1,6,3.5,true,true,true,null,"Face-to-face"));
        courses.add(new Course("MGMT1001","Managing Organisations and People","Managing Organisations and People is a foundational core course offered in the main bachelor degree programs. This course introduces students to the knowledge and skills required to successfully manage organisations and people in a global economy, based on contemporary research and practice. The course is designed to provide strong foundations for the development of future organisational leaders and managers who will be able to successfully respond to complex and turbulent environments, promote and sustain strategic advantage, ensure ethical and social responsibility in business practice and decision making, and manage changing social, political and technological factors both inside and outside the organisation, in an increasingly global and diverse workplace.",1,6,3.6,true,true,true,null,"Face-to-face"));
        courses.add(new Course("ECON1203","Business and Economic Statistics", "This course introduces students to basic statistical concepts and methods that are widely used in economics, finance, accountancy, marketing and, more generally, business. Emphasis is placed on applying statistical methods to draw inferences from sample data as an aid to informed decision-making. Course topics include: descriptive statistics, probability distributions, point and interval estimation of parameters, hypothesis testing, and regression models. Students will learn to solve statistical problems in an Excel spreadsheet environment. This course provides the basis for further study of statistical and econometric methods.",1,6,4.5,true,true,true,"Excluded: MATH2841, MATH2801, MATH2901, MATH2099, ACTL2002 & ACTL2131. Prerequisite: Must not be enrolled in Program 3715 or 3764","Face-to-face"));
        courses.add(new Course("MATH1041","Statistics for Life and Social Sciences","Probability, random variables, independence. Discrete distributions, Poisson and binomial distributions. Data analysis, Descriptive statistics. Sampling, Continuous distributions, the normal distribution. Estimation of mean and variance. Tests of hypotheses. Linear regression and correlation. Tests for goodness of fit. Bayesian statistics. Assumed knowledge: As for MATH1031Note: This course is not intended for students who propose to study a substantial amount of Mathematics beyond first year level. Many later year courses in Mathematics have completion of MATH1231, MATH1241 or MATH1251 as a prerequisite.",1,6,6,true,true,true,"Excluded: MATH2841", "Face-to-face"));
        courses.add(new Course("ACCT1511","Accounting and Financial Management 1B","Taken together, the accounting course in the compulsory core (ACCT1501) and this accounting course form an integrated study program designed to give students an understanding of the way in which financial information is generated and used, and to provide an appropriate platform for further study in accounting. On completion the first year accounting courses seek to develop students’: technical competence in recording economic events in the accounting system; a critical understanding of key technical terms and concepts so as to interpret accounting information and reports in the financial press; an ability to argue a reasoned position on key questions of accounting theory and practice; and familiarity with institutional structures that affect the practice of accounting. Topics covered in this course will include accounting for non-current assets and liabilities, revenues and expenses, balance sheet and income statement preparation, cash flow statements, ratio analysis, accounting policy choice and further detail on management accounting (including costing systems and budgeting).", 1,6,3,true,true,true,null,"Face-to-face"));
        courses.add(new Course("ECON1101","Microeconomics 1", "Economics is a social science which studies the ways in which people interact with one another and make decisions in a world with limited resources. The goal of this course is to provide you with the basic tools to “think like an economist” – that is, to be able to use basic economic principles to ask and answer questions about how the world works or the effects of policies. We will cover topics such as how individuals or firms make decisions about the demand or supply of a product, how we can determine the efficiency of a market, and how we evaluate the costs and benefits of government intervention in a market.",1,6,4.5,true,true,true,null,"Face-to-face"));
        courses.add(new Course("INFS2603","Business Analysis", "This is a Level 2 course that continues students’ study of Information Systems by furthering their knowledge and skills in relation to business systems analysis. This course utilizes methodologies and approaches such as Agile Scrum, Design Thinking and Object-Orientation to analyse and design business information systems. In lectures, students will be introduced to a range of methods, tools and techniques used in planning, analysing and designing information systems. During weekly practical workshops, students will get a chance to apply their theoretical knowedge to understand real-world scenarios.",2,6,4,false,false,true,null,"Face-to-face"));
        courses.add(new Course("INFS2605","Intermediate Business Programming","This is a Level 2 Information Systems (IS) course that continues students’ study of IS by furthering their knowledge and skills in relation to business application development. The course continues the study of Java programming from INFS1609 (Fundamentals of Business Programming) and examines contemporary approaches to software development. In lectures, students will study a range of topics from advanced Java concepts, software development frameworks and practices, to user experience and design. During weekly workshop tutorials, students will engage in the practical component of the course and problem-solving exercises through the development of Java applications using the NetBeans Integrated Development Environment (IDE).\n" +
                "\n" +
                "The topics that are covered in INFS2605 build on the programming skills introduced in INFS1609 and the database skills in INFS1603, providing students with a thorough review of software development processes and object-oriented programming principles. Students will then expand their application development skills and knowledge through the study of Model View Controller (MVC) architecture, event-driven programming, Graphical User Interfaces (GUI) and User Experience (UX) design. \n" +
                "\n" +
                "Specifically, the course introduces students to the development of JavaFX GUI applications, using Scenebuilder. Building on this, students are then provided with an overview of exception handling and taught how to develop basic database applications using Java Database Connectivity (JDBC), an application programming interface (API), which defines how a client may access a database. The course also provides an introduction to API’s that facilitate the development of reporting functionalities (e.g. exporting data to excel) from database applications. The course will also briefly cover basic web-development skills, design languages (material design) as well as UX principles and practices in the design of software products.",2,6,3.6,true,false,true,null,"Face-to-face"));
        courses.add(new Course("INFS2608","Database Management & Big Data Infrastructures","INFS2608 is a Level 2 Information Systems (IS) course that continues students’ study of IS by covering various advanced topics pertinent to big data management, which includes both relational and analytical data system infrastructure. It will explain advanced concepts used to design and manage relational and analytical big data system infrastructure. Through this course, students will learn to evaluate issues associated with big data management and business data analytics such as data quality and security. In taking this course, students will be provided with tasks and assignments that will aid in refining their ability to evaluate the value of data focused infrastructures.",2,6,4,true,false,false,"Excludes: INFS3608 and INFS5926","Face-to-face"));
        courses.add(new Course("INFS2621","Enterprise Systems","This is a Level 2 Information Systems (IS) course that continues the students’ study of IS by introducing students to Enterprise Systems used in today’s networked organisations, specifically, how they can be used by organisations to support data analytics and to run their operations more efficiently and effectively. Students will learn to develop models for selected business process including procurement, fulfilment and logistics. Students will learn to communicate the challenges in the selection, acquisition and implementation of Enterprise Systems.",2,6,4,false,true,false,"Excludes INFS5621","Face-to-face"));
        courses.add(new Course("INFS3603","Introduction to Business Analytics","This is a Level 3 Information Systems (IS) course and a foundational course in Business Analytics (BA). This course provides students with an understanding of business needs and technology trends driving investment in business analytics and big data technologies. The course also presents the fundamentals of implementing and managing business analytics in organisations. In lectures, students will learn business analytics methods and tools as well as the challenges associated with implementing business analytics projects. Through real-world case studies, students will develop their understanding of the applications of business analytics as well as the social and ethical implications of business analytics. Students will also improve their critical thinking, problem-solving, research, communication and team-working skills through group assignments.\n" +
                "\n" +
                "Topics  covered in this course include: decision-making process; business analytics concepts, methods, and frameworks; frameworks for putting analytics to work; the governance, oversight and business value gained from business analytics within organisations; ethical and social implications of business analytics; and future directions for business analytics. \n" +
                "\n" +
                "SAS Visual Analytics will be used in this course.",3,6,4,true,true,false,null,"Face-to-face"));
        courses.add(new Course("INFS3604","Business Process Management","To meet the demands of today’s competitive marketplace, enterprise processes must be lean and customer focussed. This course looks at ways in which business processes can be analysed, redesigned, and improved thus ensuring that they are meeting the needs of customers and the enterprise. A business process is a set of related activities that jointly realise a business goal in an organisational and technical environment. These processes take place in a single organisation but may need to interact with processes in other organisations. Business process management (BPM) is concerned with the concepts, methods, and techniques that support the design, improvement, management, configuration, enactment, and analysis of business processes that deliver lean and customer focused business processes. BPM includes process modelling that explicitly represents processes – once they are defined, processes can be analysed, improved, and enacted. Software in the form of business process management systems can be used to manage business process.",3,6,3.6,false,false,true,null,"Face-to-face"));
        courses.add(new Course("INFS3605","Information Systems Innovation & Transformation","This is a Level 3 Information Systems (IS) course that concludes the students’ study of IS through the application, integration and synthesis of students’ knowledge from previous IS courses. Specifically, INFS3605 is the ‘capstone’ IS course that is centrally organised around practical, experiential, group software projects. Throughout the course, students will apply programming knowledge and teamwork skills learnt in previous courses in an applied and integrated fashion. The course begins with student groups brainstorming and developing their software project ideas and then gathering requirements. Following this, student groups engage in an iterative development process in designing and refining their software application. Specifically, students will use the agile scrum framework in developing their software project, working in two-week sprints/iterations. This hands-on project course takes a blended approach to learning, mixing online content provided through the school’s e-learning platform (Moodle) with weekly flipped workshop sessions. Throughout the course, students will perform various roles (including scrum master and product owner) and ceremonies (including sprint planning, stand-up sessions, sprint reviews, sprint retrospectives and backlog refinement), as well as utilise a number of a tools (such as kanban boards, burndown charts and planning poker).\n" +
                "\n" +
                "Overall, this capstone project course requires students to apply, integrate and build upon existing knowledge and skills learnt in previous IS courses. In particular, the course requires students to perform as agile scrum teams and develop complex software applications in an iterative and incremental manner.",3,6,3.6,true,true,false,null,"Face-to-face"));
        courses.add(new Course("INFS3617","Networking & Cyber Security","This is a Level 3 Information Systems (IS) course that continues students’ study in IS by further developing their knowledge and understanding in information technology infrastructure and security in a business environment. The course will provide students with a learning experience that encourages participation and building of ideas in regards to current issues in business data networks, telecommunications, and infrastructure along with class discussions on the topics. The course has a technical component in which students gain practical knowledge and experience in networking and IS security techniques.\n" +
                "\n" +
                "Topics to be covered in this course include inter-networked data communications and distributed data processing. Topics covered include, the business imperatives for distributed systems, systems architectural design (client/server; distributed processing, etc) layered architecture models (TCP/IP, OSI, etc), key network models and technologies, security issues related to architecture, design and technology, network configuration and management techniques.",3,6,4,true,false,false,null,"Face-to-face"));
        courses.add(new Course("INFS3634","Mobile Applications Development","This is a Level 3 Information Systems (IS) course that continues your study of IS by furthering your knowledge and skills in relation to mobile application development. Continuing from INFS2605, this course focuses on the development of software applications using the Android platform. During lectures will be provided with an overview of mobile programming concepts and tools, and engage in case studies with regards to mobile App development and the current mobile market. During the weekly practical tutorials, students will use the Android Studio Integrated development environment (IDE) in learning how to design and develop a range of mobile applications. Students will be required to evaluate the quality of their own, and peers’, coding solutions.\n" +
                "\n" +
                "This course is offered as a third-year elective from the School of Information Systems and Technology Management. A central aim of this course is to provide students with a foundational understanding of the technologies, methods and skills required to design and develop apps on the Android platform. This course aims to provide students with various concepts and skills that are essential in careers such as project designers and software developers. This course builds on from INFS1609/INFS2609 and INFS2605 and provides learning material useful for student’s project work in INFS3605.",3,6,4,true,false,true,null,"Face-to-face"));
        courses.add(new Course("INFS2631","Innovation and Technology Management","This is a Level 2 multi-disciplinary course at the intersection of information systems, entrepreneurship, and operations management. The course aims to develop students’ conceptual knowledge and practical skills regarding managing technological innovation through various phases of the innovation process. This course will analyse how small and large firms innovative, commercialise and compete in competitive markets through the development and management of technology. The course emphasises the role of crowdsourcing, social media and social networks in developing, driving and managing innovations. The course will primarily use case studies and class discussions to analyse emerging issues in technology strategy and entrepreneurship.",2,6,4,true,false,false,"Excludes INFS3631","Face-to-face"));
        courses.add(new Course("INFS3020","International Information Systems and Technology Practicum","This course affords students the opportunity to develop knowledge and understanding of international aspect of information systems/technology (IS/IT) business operations (e.g. global IS/IT teams, distributed systems development, eBusiness, and localisation management) through the firsthand observation of businesses in Asian countries such as China, India, Hong Kong, and South Korea. The central components of the course include a series of seminars and a two-week study tour to one Asian country, in which a number of leading international and national companies, including companies operating in the IS/IT sector and those in other sectors with a significant IS/IT footprint, will be visited in order to enable students to develop an appreciation of the ways in which IS/IT enabled business operations and business systems differ across national boundaries. Students are required to prepare a written assignment based on the field trip at the end of the tour based on their observations of the businesses and the country. A group presentation and personal reflection report are to be delivered prior to the end of the Term 2. ",3,6,7,false,true,false,"Good Academic Standing with minimum WAM 60 and completion of 96UOC including minimum of 36 UOC of INFS courses. You cannot enrol in this subject yourself, you need to apply.","International"));
        courses.add(new Course("INFS3632","Service and Quality Management","This is a Level 3 Information Systems (IS) course that introduces students to the key concepts in managing service operations and quality management. This course emphasises the use of data analytics to study service quality management and will teach skills and tools such as Statistical Quality Control, Six-Sigma, and Lean Operations, which are valuable for service process quality control. In lectures, students will learn the \"state of the art\" of process management of service firms and the opportunities provided by information technology and data analytics in enhancing their competitiveness. Students will be engaged in simulations, where they can apply the concepts learnt in the class to real-world settings and learn how to manage process variabilities and quality control. In a project which involves conducting a walk-through-audit to a real company of the students’ choice, they will learn how to implement a service business to meet customer satisfaction.\n" +
                "\n" +
                "The service sector is the fastest-growing sector of the economy in Australia, which represents about 70% of Australia's gross domestic product and provides significant employment opportunities to Australians. To maintain Australia's position as a leading world-class provider of services, it is important for all employees in service and the public sector to understand the concepts and tools used to design and operate processes that will deliver a high quality of services.",3,6,3.6,false,true,false,null,"Face-to-face"));
        courses.add(new Course("INFS3830","Social Media and Analytics","This is a Level 3 Information Systems (IS) course that provides an introduction to the use of social media in organisation by examining the enabling effect of social media technologies for competitive advantage and the potential insights from the vast data generated on social media platforms. Students will analyse and develop strategies related to the use of social technologies within businesses and the use of social media as for external relations (especially with customers). This course is designed to critically evaluate the potential for social media technologies to facilitate meaningful discussions in communities, consumer markets and strategic decision making. In addition to examining strategies to create and extract value from social media, the effect of social media on operational matters, social media metrics and strategic aspects of social media analytics, the course will incorporate a hands-on component using SAS software.",3,6,4,true,false,false,null,"Face-to-face"));
        courses.add(new Course("INFS3873","Business Analytics Methods","Today’s organisations operate on a global scale and collect huge volumes of data from multiple sources. Management recognises the need to learn how to gather and manage strategic data, transform it into new insights, and translate those insights into effective front-line action in order to have a better understanding of business performance and gain competitive advantage. This course will provide students with advanced business analytics methods including predictive analytics and Visual analytics. Both meaningful hands-on experience and case studies describing organisational experiences with business analytics are included. The course has a technical component in which students gain practical knowledge and skills in data mining and visual analytics.",3,6,4,false,false,true,null,"Face-to-face"));

        return courses;
    }

    public static ArrayList<Program> getPrograms(){
        ArrayList<Program> programs = new ArrayList<>();
        programs.add(new Program("3979", "Information Systems", "The Bachelor of Information Systems (BIS) degree is a highly prized qualification which provides students with information systems expertise and business skills. The program is intended to develop conceptual and practical skills. After an introductory first stage, students will learn about business systems analysis and design, data management, enterprise systems, business process management, big data business analytics, business systems infrastructure and security as well as mathematics, management accounting and commercial programming.\n" + "\n" +
                "This three year degree is designed for students interested in the use and application of IS and IT commercial environment. It combines courses that assist students to learn about the technical environment of IS as well as develop an understanding of the business implications of these systems. Organisations are always looking for 'business savvy' IS graduates who understand the business and technical issues which surround and impact their information systems.\n" + "\n" +
                "BIS graduates from this degree can target careers in areas such as: business systems analysis, information system development, communications networks analysis and development; IS security development; e-business systems development; business intelligence systems construction, business analytics and IS and IT architecture and infrastructure development and maintenance. The program includes courses from many disciplines including: Information Systems, Technology and Management, and other Commerce and Economics courses.", 144,3));
        programs.add(new Program("3964","Information Systems (Co-op) (Honours)","The BIS (Co-op) (Hons) is a full-time four year Honours degree program. It is an industry linked education program leading to the award of the qualification Bachelor of Information Systems (Co-op) (Honours). The program draws on both Information Systems and business and is intended to develop conceptual and practical skills. After an introductory first stage, students will learn about business analysis systems and design, data management, business systems infrastructure and security as well as commercial programming statistics, management accounting and commercial programming.\n" + "\n" +
                "The BIS (Co-op) (Hons) program has been designed in conjunction with Information Systems and Information Technology industry professionals to provide for the needs of Australian businesses. The program combines the requirements for the award of the degree with 18 months of coordinated industrial experience at three different sponsoring organisations (24 weeks at each). Industry Training extends outside university semesters. \n" + "\n" +
                "The program combines courses that assist students to learn about the technical environment of IS as well as develop an understanding of the business implications of these systems. Organisations are always looking for business savvy IS graduates who understand the business and technical issues which surround and impact their information systems. IS graduates from this degree can target careers in areas such as: business systems analysis, information system development, communications networks analysis and development; IS security development; e-business systems development; business intelligence systems construction, and IS and IT architecture and infrastructure development and maintenance.",
                192,4));
        programs.add(new Program("3584","Commerce / Information Systems","This 4 year dual program leads to the award of a Bachelor of Commerce/Bachelor of Information Systems (BCom/BIS) and will meet the needs of students who want a strong, focused and highly regarded business degree combined with an Information Systems degree. Organisations are always looking for \"business savvy\"? IS graduates who understand the business and technical issues which surround and impact their information systems. As part of the degree program students will complete a major stream in both Information Systems (IS) and an approved disciplinary stream within the UNSW Business School.\n" + "\n" +
                "In selecting their combination of majors, students should note that while there is a wide range of choice, not every combination may be able to be completed in 4 years of full-time study. Students are also not able to take a modern language as their major.",144,3));
        return programs;
    }

    public static ArrayList<Prereq> getPrereqs(){
        ArrayList<Prereq> prereqs = new ArrayList<>();

        prereqs.add(new Prereq("INFS2101","INFS1609"));
        prereqs.add(new Prereq("INFS2101","INFS2603"));
        prereqs.add(new Prereq("INFS2603","INFS1602"));
        prereqs.add(new Prereq("INFS2603","INFS1603"));
        prereqs.add(new Prereq("INFS2605","INFS1603"));
        prereqs.add(new Prereq("INFS2605","INFS1609"));
        prereqs.add(new Prereq("INFS2608","INFS1603"));
        prereqs.add(new Prereq("INFS2621","INFS1602"));
        prereqs.add(new Prereq("INFS2631","INFS1602"));
        prereqs.add(new Prereq("INFS3202","INFS2101"));
        prereqs.add(new Prereq("INFS3303","INFS3202"));
        prereqs.add(new Prereq("INFS3603","INFS1602"));
        prereqs.add(new Prereq("INFS3604","INFS2603"));
        prereqs.add(new Prereq("INFS3605","INFS3634"));
        prereqs.add(new Prereq("INFS3617","INFS1602"));
        prereqs.add(new Prereq("INFS3632","INFS1602"));
        prereqs.add(new Prereq("INFS3634","INFS2605"));
        prereqs.add(new Prereq("INFS3634","INFS2608"));
        prereqs.add(new Prereq("INFS3830","INFS3603"));
        prereqs.add(new Prereq("INFS3873","INFS3603"));
        prereqs.add(new Prereq("ACCT1511", "ACCT1501"));


        return prereqs;
    }

    public static ArrayList<Stream> getStreams() {
        ArrayList<Stream> streams = new ArrayList<>();
        streams.add(new Stream("INFS1C", "Stage 1 Compulsory Core",30,false));
        streams.add(new Stream("INFS1CA","Stage 1 Compulsory Core Option 1", 6, false));
        streams.add(new Stream("INFS1CB", "Stage 1 Compulsory Core Option 2", 6, false));
        streams.add(new Stream("INFS2C","Stage 2 Compulsory Core",24,false));
        streams.add(new Stream("39793C","Stage 3 Compulsory Core",30,false));
        streams.add(new Stream("3979E","INFS Stage 2/3 Electives (choose 2)", 12, false));
        streams.add(new Stream("3979F","Free Electives",24,false));
        streams.add(new Stream("GENED","General Education",12,false));
        //insert more streams here
        return streams;
    }

    public static ArrayList<ProgramStream> getProgramStreams() {
        ArrayList<ProgramStream> programStreams = new ArrayList<>();
        programStreams.add(new ProgramStream("3979","INFS1C"));
        programStreams.add(new ProgramStream("3979","INFS1CA"));
        programStreams.add(new ProgramStream("3979","INFS1CB"));
        programStreams.add(new ProgramStream("3979","INFS2C"));
        programStreams.add(new ProgramStream("3979","39793C"));
        programStreams.add(new ProgramStream("3979","3979E"));
        programStreams.add(new ProgramStream("3979","3979F"));
        programStreams.add(new ProgramStream("3979","GENED"));

        //insert more programstreams here
        return programStreams;
    }

    public static ArrayList<StreamCourse> getStreamCourse() {
        ArrayList<StreamCourse> streamCourses = new ArrayList<>();
        streamCourses.add(new StreamCourse("INFS1C", "INFS1602", true));
        streamCourses.add(new StreamCourse("INFS1C", "INFS1603", true));
        streamCourses.add(new StreamCourse("INFS1C", "INFS1609", true));
        streamCourses.add(new StreamCourse("INFS1C", "INFS1501", true));
        streamCourses.add(new StreamCourse("INFS1C", "MGMT1001", true));
        streamCourses.add(new StreamCourse("INFS1CA", "ECON1203", false));
        streamCourses.add(new StreamCourse("INFS1CA", "MATH1041", false));
        streamCourses.add(new StreamCourse("INFS1CB", "ACCT1511", false));
        streamCourses.add(new StreamCourse("INFS1CB", "ECON1101", false));
        streamCourses.add(new StreamCourse("INFS2C", "INFS2603", true));
        streamCourses.add(new StreamCourse("INFS2C", "INFS2605", true));
        streamCourses.add(new StreamCourse("INFS2C", "INFS2608", true));
        streamCourses.add(new StreamCourse("INFS2C", "INFS2621", true));
        streamCourses.add(new StreamCourse("39793C", "INFS3603", true));
        streamCourses.add(new StreamCourse("39793C", "INFS3604", true));
        streamCourses.add(new StreamCourse("39793C", "INFS3605", true));
        streamCourses.add(new StreamCourse("39793C", "INFS3617", true));
        streamCourses.add(new StreamCourse("39793C", "INFS3634", true));
        streamCourses.add(new StreamCourse("3979E", "INFS2631", false));
        streamCourses.add(new StreamCourse("3979E", "INFS3020", false));
        streamCourses.add(new StreamCourse("3979E", "INFS3632", false));
        streamCourses.add(new StreamCourse("3979E", "INFS3830", false));
        streamCourses.add(new StreamCourse("3979E", "INFS3873", false));

        //insert more stream courses here
        return streamCourses;
    }

}
