package com.example.mydegree.Room;

import java.lang.reflect.Array;
import java.util.ArrayList;

public class InsertData {

    public static ArrayList<Course> getCourses(){
        ArrayList<Course> courses = new ArrayList<>();
        courses.add(0, new Course("3979","Information Systems",null,0,0,0,false,false,false,null,null));
        courses.add(1,new Course("3964", "Information Systems (Co-op) (Hons)", null,0,0,0,false,false,false,null,null));
        courses.add(2,new Course("3584", "Commerce / Information Systems", null, 0,0,0,false,false,false,null,null));
        courses.add(new Course("INFS1602","Digital Transformation in Business","This is a foundational (Level 1) Information Systems (IS) course that introduces students to the use of IS in business and society. As an overarching theme, INFS1602 examines the issues and management of IS in relation to human behaviour and its consequences. Through this course, students will learn to appreciate existing and emerging technologies affecting businesses, business relationships and their products and services. In taking this course, students will be provided with tasks and assignments that will aid in refining their professional business skills and the ability to evaluate the value of technology to businesses. This includes communication and group work skills, time management and research skills.\n" +
                "\n" +
                "The topics that are covered in INFS1602 include understanding the role of Information Systems and IS Professionals in Global Business, the relationship between Information Systems, Organisations, and Strategy, the dominant Business Models enabled by the Internet and Web 2.0 technology. The course will also explore contemporary technologyenabled phenomena that are disruptive to the current business landscape. The course also touches on popular enterprise-level information systems such as Enterprise Systems, Supply Chain and Customer Relationship Management Systems and the emergence of business intelligence in supporting organisation decision making. The course also involves discussion of the considerations behind the acquisition and building of IS and the issues common to the management of IS projects. Lastly, the course addresses the need to secure the IS and the potential ethical and social issues faced by businesses in relation to their use of IS.",1,6,4.5, true,true,true, null, "Face-to-face"));
        courses.add(new Course("INFS1603", "Introduction to Business Databases","This is a foundational (Level 1) Information Systems (IS) course that introduces students to the concepts, techniques, and technologies relevant for creating and managing business databases. It will explain the major components of IS, which are critical to capturing, transmitting, storing, retrieving, manipulating and displaying information used in business processes. Through this course, students will be exposed to the fundamental knowledge of business databases, which are foundational for many advanced courses. Students will be given tasks and assignments to help them acquire the ability to create and manage business databases.",1,6,4,true,true,false,null,"Face-to-face"));
        courses.add(new Course("INFS1609","Fundamentals of Business Programming", "This is a foundational (Level 1) Information Systems (IS) course that introduces students to application programming. The course provides a first step towards learning the principles of object-oriented programming through the Java programming language. Programming refers to the development of software, which is also called a program. Essentially, software contains the instructions that tell computerised devices what to do. In lectures, students will be introduced to the theoretical component of the course, learning fundamental programming concepts. During weekly workshop tutorials, students will engage in the practical component of the course, learning how to write code using the NetBeans Integrated Development Environment.\n" +
                "\n" +
                "The topics that are covered in INFS1609 introduce students to the fundamentals of Java programming. This begins with an overview of data types and methods before introducing students to small problem-solving exercises that require the use of conditional statements, loops and arrays (including multi-dimensional arrays and array lists). Students are then introduced to the topics of modular programming, testing and debugging (using JUNIT). Finally, having gained a general understanding of these concepts, students further explore the principles of object-oriented programming, including objects, classes, abstraction, polymorphism, inheritance and encapsulation.",1,6,4,true,false,true,"Not in INFS2609/COMP1400","Face-to-face"));
        courses.add(new Course("ACCT1501","Accounting and Financial Management 1A","The compulsory core accounting unit will have a preparer perspective. It will provide an introduction to basic concepts in accounting and their application for decision making by a wide range of potential users (e.g., shareholders, investment analysts, lenders, managers etc). This unit should benefit students who wish to specialise in accounting, and will also be of value to students whose primary interest lies elsewhere in the field of business.\n" +
                "\n" +
                "On completion, students should have a clear understanding of the accounting process and the language of accounting to enable communication with an accounting professional, understand the relevance of accounting information for informed decision making by a wide range of potential users, and have the ability to analyse and interpret accounting information. Topics covered will include the accounting equation, general purpose financial reports, cash and accrual accounting, adjustments, internal control, financial statement analysis, and interpreting and preparing information for managers to use in planning, decision making and control.",1,6,3.5,true,true,true,null,"Face-to-face"));
        courses.add(new Course("MGMT1001","Managing Organisations and People","Managing Organisations and People is a foundational core course offered in the main bachelor degree programs. This course introduces students to the knowledge and skills required to successfully manage organisations and people in a global economy, based on contemporary research and practice. The course is designed to provide strong foundations for the development of future organisational leaders and managers who will be able to successfully respond to complex and turbulent environments, promote and sustain strategic advantage, ensure ethical and social responsibility in business practice and decision making, and manage changing social, political and technological factors both inside and outside the organisation, in an increasingly global and diverse workplace.",1,6,3.6,true,true,true,null,"Face-to-face"));
        courses.add(new Course("ECON1203","Business and Economic Statistics", "This course introduces students to basic statistical concepts and methods that are widely used in economics, finance, accountancy, marketing and, more generally, business. Emphasis is placed on applying statistical methods to draw inferences from sample data as an aid to informed decision-making. Course topics include: descriptive statistics, probability distributions, point and interval estimation of parameters, hypothesis testing, and regression models. Students will learn to solve statistical problems in an Excel spreadsheet environment. This course provides the basis for further study of statistical and econometric methods.",1,6,4.5,true,true,true,"Excluded: MATH2841, MATH2801, MATH2901, MATH2099, ACTL2002 & ACTL2131. Prerequisite: Must not be enrolled in Program 3715 or 3764","Face-to-face"));
        courses.add(new Course("MATH1041","Statistics for Life and Social Sciences","Probability, random variables, independence. Discrete distributions, Poisson and binomial distributions. Data analysis, Descriptive statistics. Sampling, Continuous distributions, the normal distribution. Estimation of mean and variance. Tests of hypotheses. Linear regression and correlation. Tests for goodness of fit. Bayesian statistics. Assumed knowledge: As for MATH1031Note: This course is not intended for students who propose to study a substantial amount of Mathematics beyond first year level. Many later year courses in Mathematics have completion of MATH1231, MATH1241 or MATH1251 as a prerequisite.",1,6,6,true,true,true,"Excluded: MATH2841", "Face-to-face"));
        courses.add(new Course("ACCT1511","Accounting and Financial Management 1B","Taken together, the accounting course in the compulsory core (ACCT1501) and this accounting course form an integrated study program designed to give students an understanding of the way in which financial information is generated and used, and to provide an appropriate platform for further study in accounting. On completion the first year accounting courses seek to develop students’: technical competence in recording economic events in the accounting system; a critical understanding of key technical terms and concepts so as to interpret accounting information and reports in the financial press; an ability to argue a reasoned position on key questions of accounting theory and practice; and familiarity with institutional structures that affect the practice of accounting. Topics covered in this course will include accounting for non-current assets and liabilities, revenues and expenses, balance sheet and income statement preparation, cash flow statements, ratio analysis, accounting policy choice and further detail on management accounting (including costing systems and budgeting).", 1,6,3,true,true,true,null,"Face-to-face"));
        courses.add(new Course("ECON1101","Microeconomics 1", "Economics is a social science which studies the ways in which people interact with one another and make decisions in a world with limited resources. The goal of this course is to provide you with the basic tools to 'think like an economist' – that is, to be able to use basic economic principles to ask and answer questions about how the world works or the effects of policies. We will cover topics such as how individuals or firms make decisions about the demand or supply of a product, how we can determine the efficiency of a market, and how we evaluate the costs and benefits of government intervention in a market.",1,6,4.5,true,true,true,null,"Face-to-face"));
        courses.add(new Course("INFS2603","Business Analysis", "This is a Level 2 course that continues students’ study of Information Systems by furthering their knowledge and skills in relation to business systems analysis. This course utilizes methodologies and approaches such as Agile Scrum, Design Thinking and Object-Orientation to analyse and design business information systems. In lectures, students will be introduced to a range of methods, tools and techniques used in planning, analysing and designing information systems. During weekly practical workshops, students will get a chance to apply their theoretical knowedge to understand real-world scenarios.",2,6,4,false,false,true,null,"Face-to-face"));
        courses.add(new Course("INFS2605","Intermediate Business Programming","This is a Level 2 Information Systems (IS) course that continues students’ study of IS by furthering their knowledge and skills in relation to business application development. The course continues the study of Java programming from INFS1609 (Fundamentals of Business Programming) and examines contemporary approaches to software development. In lectures, students will study a range of topics from advanced Java concepts, software development frameworks and practices, to user experience and design. During weekly workshop tutorials, students will engage in the practical component of the course and problem-solving exercises through the development of Java applications using the NetBeans Integrated Development Environment (IDE).\n" +
                "\n" +
                "The topics that are covered in INFS2605 build on the programming skills introduced in INFS1609 and the database skills in INFS1603, providing students with a thorough review of software development processes and object-oriented programming principles. Students will then expand their application development skills and knowledge through the study of Model View Controller (MVC) architecture, event-driven programming, Graphical User Interfaces (GUI) and User Experience (UX) design. \n" +
                "\n" +
                "Specifically, the course introduces students to the development of JavaFX GUI applications, using Scenebuilder. Building on this, students are then provided with an overview of exception handling and taught how to develop basic database applications using Java Database Connectivity (JDBC), an application programming interface (API), which defines how a client may access a database. The course also provides an introduction to API’s that facilitate the development of reporting functionalities (e.g. exporting data to excel) from database applications. The course will also briefly cover basic web-development skills, design languages (material design) as well as UX principles and practices in the design of software products.",2,6,3.6,true,false,true,null,"Face-to-face"));
        courses.add(new Course("INFS2608","Database Management & Big Data Infrastructures","INFS2608 is a Level 2 Information Systems (IS) course that continues students’ study of IS by covering various advanced topics pertinent to big data management, which includes both relational and analytical data system infrastructure. It will explain advanced concepts used to design and manage relational and analytical big data system infrastructure. Through this course, students will learn to evaluate issues associated with big data management and business data analytics such as data quality and security. In taking this course, students will be provided with tasks and assignments that will aid in refining their ability to evaluate the value of data focused infrastructures.",2,6,4,true,false,false,"Excludes: INFS3608 and INFS5926","Face-to-face"));
        courses.add(new Course("INFS2621","Enterprise Systems","This is a Level 2 Information Systems (IS) course that continues the students’ study of IS by introducing students to Enterprise Systems used in today’s networked organisations, specifically, how they can be used by organisations to support data analytics and to run their operations more efficiently and effectively. Students will learn to develop models for selected business process including procurement, fulfilment and logistics. Students will learn to communicate the challenges in the selection, acquisition and implementation of Enterprise Systems.",2,6,4,false,true,false,"Excludes INFS5621","Face-to-face"));
        courses.add(new Course("INFS3603","Introduction to Business Analytics","This is a Level 3 Information Systems (IS) course and a foundational course in Business Analytics (BA). This course provides students with an understanding of business needs and technology trends driving investment in business analytics and big data technologies. The course also presents the fundamentals of implementing and managing business analytics in organisations. In lectures, students will learn business analytics methods and tools as well as the challenges associated with implementing business analytics projects. Through real-world case studies, students will develop their understanding of the applications of business analytics as well as the social and ethical implications of business analytics. Students will also improve their critical thinking, problem-solving, research, communication and team-working skills through group assignments.\n" +
                "\n" +
                "Topics  covered in this course include: decision-making process; business analytics concepts, methods, and frameworks; frameworks for putting analytics to work; the governance, oversight and business value gained from business analytics within organisations; ethical and social implications of business analytics; and future directions for business analytics. \n" +
                "\n" +
                "SAS Visual Analytics will be used in this course.",3,6,4,true,true,false,null,"Face-to-face"));
        courses.add(new Course("INFS3604","Business Process Management","To meet the demands of today’s competitive marketplace, enterprise processes must be lean and customer focussed. This course looks at ways in which business processes can be analysed, redesigned, and improved thus ensuring that they are meeting the needs of customers and the enterprise. A business process is a set of related activities that jointly realise a business goal in an organisational and technical environment. These processes take place in a single organisation but may need to interact with processes in other organisations. Business process management (BPM) is concerned with the concepts, methods, and techniques that support the design, improvement, management, configuration, enactment, and analysis of business processes that deliver lean and customer focused business processes. BPM includes process modelling that explicitly represents processes – once they are defined, processes can be analysed, improved, and enacted. Software in the form of business process management systems can be used to manage business process.",3,6,3.6,false,false,true,null,"Face-to-face"));
        courses.add(new Course("INFS3605","Information Systems Innovation & Transformation","This is a Level 3 Information Systems (IS) course that concludes the students’ study of IS through the application, integration and synthesis of students’ knowledge from previous IS courses. Specifically, INFS3605 is the ‘capstone’ IS course that is centrally organised around practical, experiential, group software projects. Throughout the course, students will apply programming knowledge and teamwork skills learnt in previous courses in an applied and integrated fashion. The course begins with student groups brainstorming and developing their software project ideas and then gathering requirements. Following this, student groups engage in an iterative development process in designing and refining their software application. Specifically, students will use the agile scrum framework in developing their software project, working in two-week sprints/iterations. This hands-on project course takes a blended approach to learning, mixing online content provided through the school’s e-learning platform (Moodle) with weekly flipped workshop sessions. Throughout the course, students will perform various roles (including scrum master and product owner) and ceremonies (including sprint planning, stand-up sessions, sprint reviews, sprint retrospectives and backlog refinement), as well as utilise a number of a tools (such as kanban boards, burndown charts and planning poker).\n" +
                "\n" +
                "Overall, this capstone project course requires students to apply, integrate and build upon existing knowledge and skills learnt in previous IS courses. In particular, the course requires students to perform as agile scrum teams and develop complex software applications in an iterative and incremental manner.",3,6,3.6,true,true,false,null,"Face-to-face"));
        courses.add(new Course("INFS3617","Networking & Cyber Security","This is a Level 3 Information Systems (IS) course that continues students’ study in IS by further developing their knowledge and understanding in information technology infrastructure and security in a business environment. The course will provide students with a learning experience that encourages participation and building of ideas in regards to current issues in business data networks, telecommunications, and infrastructure along with class discussions on the topics. The course has a technical component in which students gain practical knowledge and experience in networking and IS security techniques.\n" +
                "\n" +
                "Topics to be covered in this course include inter-networked data communications and distributed data processing. Topics covered include, the business imperatives for distributed systems, systems architectural design (client/server; distributed processing, etc) layered architecture models (TCP/IP, OSI, etc), key network models and technologies, security issues related to architecture, design and technology, network configuration and management techniques.",3,6,4,true,false,false,null,"Face-to-face"));
        courses.add(new Course("INFS3634","Mobile Applications Development","This is a Level 3 Information Systems (IS) course that continues your study of IS by furthering your knowledge and skills in relation to mobile application development. Continuing from INFS2605, this course focuses on the development of software applications using the Android platform. During lectures will be provided with an overview of mobile programming concepts and tools, and engage in case studies with regards to mobile App development and the current mobile market. During the weekly practical tutorials, students will use the Android Studio Integrated development environment (IDE) in learning how to design and develop a range of mobile applications. Students will be required to evaluate the quality of their own, and peers’, coding solutions.\n" +
                "\n" +
                "This course is offered as a third-year elective from the School of Information Systems and Technology Management. A central aim of this course is to provide students with a foundational understanding of the technologies, methods and skills required to design and develop apps on the Android platform. This course aims to provide students with various concepts and skills that are essential in careers such as project designers and software developers. This course builds on from INFS1609/INFS2609 and INFS2605 and provides learning material useful for student’s project work in INFS3605.",3,6,4,true,false,true,null,"Face-to-face"));
        courses.add(new Course("INFS2631","Innovation and Technology Management","This is a Level 2 multi-disciplinary course at the intersection of information systems, entrepreneurship, and operations management. The course aims to develop students’ conceptual knowledge and practical skills regarding managing technological innovation through various phases of the innovation process. This course will analyse how small and large firms innovative, commercialise and compete in competitive markets through the development and management of technology. The course emphasises the role of crowdsourcing, social media and social networks in developing, driving and managing innovations. The course will primarily use case studies and class discussions to analyse emerging issues in technology strategy and entrepreneurship.",2,6,4,true,false,false,"Excludes INFS3631","Face-to-face"));
        courses.add(new Course("INFS3020","International Information Systems and Technology Practicum","This course affords students the opportunity to develop knowledge and understanding of international aspect of information systems/technology (IS/IT) business operations (e.g. global IS/IT teams, distributed systems development, eBusiness, and localisation management) through the firsthand observation of businesses in Asian countries such as China, India, Hong Kong, and South Korea. The central components of the course include a series of seminars and a two-week study tour to one Asian country, in which a number of leading international and national companies, including companies operating in the IS/IT sector and those in other sectors with a significant IS/IT footprint, will be visited in order to enable students to develop an appreciation of the ways in which IS/IT enabled business operations and business systems differ across national boundaries. Students are required to prepare a written assignment based on the field trip at the end of the tour based on their observations of the businesses and the country. A group presentation and personal reflection report are to be delivered prior to the end of the Term 2. ",3,6,7,false,true,false,"Good Academic Standing with minimum WAM 60 and completion of 96UOC including minimum of 36 UOC of INFS courses. You cannot enrol in this subject yourself, you need to apply.","International"));
        courses.add(new Course("INFS3632","Service and Quality Management","This is a Level 3 Information Systems (IS) course that introduces students to the key concepts in managing service operations and quality management. This course emphasises the use of data analytics to study service quality management and will teach skills and tools such as Statistical Quality Control, Six-Sigma, and Lean Operations, which are valuable for service process quality control. In lectures, students will learn the \"state of the art\" of process management of service firms and the opportunities provided by information technology and data analytics in enhancing their competitiveness. Students will be engaged in simulations, where they can apply the concepts learnt in the class to real-world settings and learn how to manage process variabilities and quality control. In a project which involves conducting a walk-through-audit to a real company of the students’ choice, they will learn how to implement a service business to meet customer satisfaction.\n" +
                "\n" +
                "The service sector is the fastest-growing sector of the economy in Australia, which represents about 70% of Australia's gross domestic product and provides significant employment opportunities to Australians. To maintain Australia's position as a leading world-class provider of services, it is important for all employees in service and the public sector to understand the concepts and tools used to design and operate processes that will deliver a high quality of services.",3,6,3.6,false,true,false,null,"Face-to-face"));
        courses.add(new Course("INFS3830","Social Media and Analytics","This is a Level 3 Information Systems (IS) course that provides an introduction to the use of social media in organisation by examining the enabling effect of social media technologies for competitive advantage and the potential insights from the vast data generated on social media platforms. Students will analyse and develop strategies related to the use of social technologies within businesses and the use of social media as for external relations (especially with customers). This course is designed to critically evaluate the potential for social media technologies to facilitate meaningful discussions in communities, consumer markets and strategic decision making. In addition to examining strategies to create and extract value from social media, the effect of social media on operational matters, social media metrics and strategic aspects of social media analytics, the course will incorporate a hands-on component using SAS software.",3,6,4,true,false,false,null,"Face-to-face"));
        courses.add(new Course("INFS3873","Business Analytics Methods","Today’s organisations operate on a global scale and collect huge volumes of data from multiple sources. Management recognises the need to learn how to gather and manage strategic data, transform it into new insights, and translate those insights into effective front-line action in order to have a better understanding of business performance and gain competitive advantage. This course will provide students with advanced business analytics methods including predictive analytics and Visual analytics. Both meaningful hands-on experience and case studies describing organisational experiences with business analytics are included. The course has a technical component in which students gain practical knowledge and skills in data mining and visual analytics.",3,6,4,false,false,true,null,"Face-to-face"));
        courses.add(new Course("INFS2101", "Industry Placement 1", "This course provides scholars with a practical application of the fundamental principles of information systems and technology management in an industry environment. This course is only available to Information Systems, UNSW Business School Co-op Scholars who are enrolled in the BIS (Co-op) (Hons) 3964 or the BCom IS (Co-op) 3554 Degree Programs.", 2, 12, 36.5, true, false, false, "Enrolled in plan (INFSCH3964 OR INFSCH3971) AND (INFS1609 OR INFS2609) AND INFS 2603; OR Enrolled in plan (INFSB13554) AND INFS2603", "Face-to-face"));

        courses.add(new Course("INFS3202", "Industry Placement 2", "This course provides scholars with a practical application of the fundamental principles of information systems and technology management in an industry environment. This course is only available to Information Systems, UNSW Business School Co-op Scholars who are enrolled in the BIS (Co-op) (Hons) 3964 or the BCom IS (Co-op) 3554 Degree Programs.", 3, 6, 36.5, true, true, false, "Enrolled in plan (INFSB13554 OR INFSCH3971 OR INFSCH3964)", "Face-to-face"));

        courses.add(new Course("INFS3303", "Industry Placement 3", "This course provides scholars with a practical application of the advanced principles of information systems and technology management in an industry environment. The course also provides scholars with the opportunity to further develop and enhance their communication and professional skills. This course is only available to Information Systems, UNSW Business School Co-op Scholars who are enrolled in the BIS (Coop) 3964 or the BCom IS(Coop) 3554 Degree Programs.", 3, 6, 36.5, false, true, true, "Enrolled in (Plan INFSB13554 or INFSCH3964 or INFSCH3971)", "Face-to-face"));

        courses.add(new Course("INFS4831", "Information Systems Consulting", "This course focuses on the key concepts, practices and issues in engaging and providing IT consulting services, from both the client and the consultant perspectives. The course examines the value propositions of IT consulting, how IT consultants engage with organisations and key stakeholders, and how they help analyse and solve business problems. The course seeks to familiarise you with the IT consulting process, common consulting frameworks and the benefits and limitations related to their use, key types of IT consulting engagements, and current trends in IT consulting related to the opportunities and challenges brought about by rapidly advancing technologies.", 4, 6, 3.6, true, false, false, "Prerequisite: Enrolled in Honours majoring in Information Systems.", "Face-to-face"));

        courses.add(new Course("INFS4854", "IS Strategy & Management", "This is a Level 4 Information Systems (IS) course that familiarises students with the key concepts, practices and issues in the strategic management of IS. The lectures cover theoretical and practical considerations across a variety of strategic IS management issues, which are further examined and applied in the weekly seminars. The course aims to equip students with the foundational skills needed to meaningfully participate in, or interact with, this aspect of IT management.\n" +
                "\n" +
"The course covers four key themes. It begins with a discussion of the strategic value of IT, including the role of business-IT alignment in realising that value. Second, the course looks at strategic IT decision processes, including planned and emergent strategy-making and governance. Third, the course considers strategy implementation issues, including the role of IT leadership, project management, and sourcing decisions. The course closes with a discussion of the strategic role of IT-enabled innovation and current trends in IT strategy.", 4, 6, 3.6, false, true, false, "Prerequisite: Enrolled in Honours majoring in Information Systems.", "Face-to-face"));

        courses.add(new Course("INFS4858", "Managing Complex Projects", "This is a Level 4 Information Systems (IS) course that provides students with a comprehensive introduction to project management in an IS context that is also applicable to other contexts in which project management principles apply.\n" +
                "\n" +
"This course aims to equip you with both theory and practical skills in the management of complex projects that are part of large scale programmes. These skills are critically important to a range of careers in business, for students who intend to be project managers as well as those who will work as part of a project team.\n" +
"\n" +
"The course is taught in a flipped-learning environment in which you will be learning by action, and thus experience the key phases of the project management cycle and, as a member of a multi-cultural and multi-skilled project team, you will use various tools and methods to plan each of the phases of the project. The course will consider both theoretical and practical perspectives and equip you with the necessary skills to be able to better manage or participate in projects.\n" +
"\n" +
"There will be a very strong emphasis on action-led teaching and teamwork. The textbook and extra on-line material will guide you during the semester. Through this, the course also aims to further develop your communication skills and teamwork skills, improve your time management and enhance your leadership skills.\n" +
"\n", 4, 6, 3.6, true, false, false, "Enrolment in Streams: Enrolled in an Honours Program majoring in Information Systems (INFSAH OR INFSBH OR INFSCH)", "Face-to-face"));

        courses.add(new Course("INFS4886", "Principles of Research Design", "This is a Level 4 Information Systems (IS) course that continues students’ study of IS by furthering their knowledge and skills in relation to research methods and analytical skills. This course focuses on the understanding of IS research methodologies.\n" +
                "\n" +
"Topics to be covered in the lectures include an overview of knowledge in research methods and techniques of data collection and analysis, SPSS, experimental research, fieldwork, grounded theory, literature review and thesis writing. During the weekly practical workshops, students will learn from key IS literature how to develop a range of research designs. Students will learn to prepare independent studies including formulating research questions and selecting a research approach, applying research methodology – designing a study and selecting specific methods and techniques appropriate for answering the research questions.\n" +
"\n", 4, 6, 3.6, false, false, true, "Prerequisite: Enrolled in Honours majoring in Information Systems.", "Face-to-face"));

        courses.add(new Course("INFS4887", "Business Research Methods", "This is a Level 4 Information Systems (IS) course that continues students’ study of IS by furthering their knowledge and skills in relation to research methods and analytical skills. Continuing from INFS4886 (Principles of Research Design), this course focuses on the understanding of IS research methodologies. Topics to be covered in the lectures include an overview of knowledge in research methods and techniques of data collection and analysis, SPSS, experimental research, fieldwork, grounded theory, literature review and thesis writing. During the weekly practical workshops, students will learn from key IS literature how to develop a range of research designs. Students will learn to prepare an independent study including formulating research questions and selecting a research approach, applying research methodology – designing a study and selecting specific methods and techniques appropriate for answering the research questions.", 4, 6, 3.6, true, false, false, "Prerequisite: INFS4886 AND enrolled in Honours majoring in Information Systems.", "Face-to-face"));

        courses.add(new Course("INFS4907", "Managing Security & Ethics in Cyberspace", "This is a Level 4 Information Systems (IS) course that builds students' awareness and knowledge of IS/IT security related issues occurring in cyberspace. It has a specific emphasis on the need for ethical viewpoints, approaches, and practices from a management perspective when addressing the multidimensional challenges and solutions posed by the IS/IT related security problems. The class will be conducted in a semi-formal workshop fashion. Using business cases and scenarios addressing various cyberspace issues, students will analyse the ethical and related implications these issues pose to stakeholders. They will learn to manage cyber-related security issues responsibly. In some situations, they may encounter dilemmas which require a careful balance in the way decisions are made.", 4, 6, 4, false, true, false, "Enrolment in Streams: Enrolled in an Honours Program majoring in Information Systems (INFSAH OR INFSBH OR INFSCH)", "Face-to-face"));

        courses.add(new Course("INFS4800", "Thesis A", "Honours students complete a thesis under the direction of a supervisor. The thesis requires the reporting of research in an approved topic area in Information Systems and Technology Management including a literature review, analysis of a research problem along with presentation of research methods and data analysis.", 4, 6, 6, true, false, false, null, "Face-to-face"));

        courses.add(new Course("INFS4801", "Thesis B", "Honours students complete a thesis under the direction of a supervisor. The thesis requires the reporting of research in an approved topic area in Information Systems and Technology Management including a literature review, analysis of a research problem along with presentation of research methods and data analysis.", 4, 6, 6, false, true, false, null, "Face-to-face"));

        courses.add(new Course("INFS4802", "Thesis C", "Honours students complete a thesis under the direction of a supervisor. The thesis requires the reporting of research in an approved topic area in Information Systems and Technology Management including a literature review, analysis of a research problem along with presentation of research methods and data analysis.", 4, 12, 6, false, false, true, null, "Face-to-face"));

        courses.add(new Course("ACCT2507", "Introduction to Accounting Research", "This course provides an introduction to accounting research. The course is designed to introduce students to the methodologies and their application in management accounting, financial accounting, and auditing research. While ACCT2507 is not a pre-requisite for the undergraduate Accounting Honours program, it is highly recommended.", 2, 6, 3, false, false, true, "Prerequisite:ACCT1511 and a mark of 80 or higher.", "Face-to-face"));

        courses.add(new Course("ACCT2522", "Management Accounting 1", "This course examines management accounting practices directed towards the effective use of organisational resources in order to create value for customers and shareholders. It focuses on three interrelated themes: first, the design and operation of management accounting systems for planning and control; second, the role of management accounting practices in supporting effective resource management and process improvement; and, third, the manner in which these practices affect and are affected by human processes within organisations. We aim to encourage critical thinking about such issues, and to improve students' abilities to address these with confidence and creativity in a professional and work-based context. The course draws upon business practice, contemporary and international research, case studies, and the applied research experiences of course participants.", 2, 6, 3.5, true, false, false, null, "Face-to-face"));

        courses.add(new Course("ACCT2542", "Corporate Financial Reporting and Analysis", "This intermediate financial accounting course is intended for students who will be involved in the preparation or use of corporate financial reports whether as accountants, financial executives, auditors, financial analysts, actuaries or legal advisors. This course builds on the foundation laid in ACCT1501 and ACCT1511 and covers financial reporting on, and analysis of, more complex business transactions, events and structures. Topics include, accounting for various types of equity investments such as subsidiaries, associates and joint ventures, tax effect accounting, disclosure issues and understanding the regulatory environment in which financial statements are prepared.", 2, 6, 3.5, false, true, false, null, "Face-to-face"));

        courses.add(new Course("ACCT3563", "Issues in Financial Reporting and Analysis","Building on the foundation laid in ACCT2542, this course covers controversial issues in financial reporting, for example leases, sharebased payments, extractive industries, biological assets,foreign currency transactions, diversified operations, and derivative financial instruments. The course also covers topical issues related to the scope and quality of financial reports. Examples include environmental reporting, and the impact of cultural differences on accounting. Students are required use relevant accounting standards, accounting theories, and ethical theories to address particular accounting issues.", 3, 6, 3, true, false, true, null, "Face-to-face"));

        courses.add(new Course("ACCT3583", "Management Accounting 2", "This course explores the link between management accounting information and strategic issues. Specifically, it focuses on how management accounting information facilitates: (1) the formulation and implementation of organisational strategy and (2) the evaluation of organisational strategy by focusing on four perspectives of strategic performance (i.e. shareholder perspective, customer perspective, internal process perspective and, learning and growth perspective).\n" +
        "\n" +
        "In this course, strategy is defined as a process of converting tangible and intangible resources to actions that will enable the organisation to compete in its chosen product markets. This is achieved by creating unique value propositions for its customers and simultaneously balancing the needs of various stakeholders (i.e. shareholders, suppliers, community and environment, and employees).", 3, 6, 3, true, false, true, null, "Face-to-face"));

        courses.add(new Course("ACCT3601", "Global Financial Reporting and Analysis", "With the increasing globalisation of business and capital markets, there is a more extensive use of cross-border financial information. This course considers the key issues in international financial reporting and analysis. Topics include: the types of differences in national financial reporting practices; the reasons for the differences; the progress of the International Accounting Standards Board in reducing the diversity; foreign exchange risk and foreign currency accounting issues; reporting and disclosure in developed countries including the USA, Japan and the members of the European Union; the role of accounting in developing countries and Eastern Europe; financial reporting in emerging capital markets including those in the Asia-Pacific region; and analysis of country-specific financial statements in the cultural, business and legal context of each country. Numerical examples and cases are used to highlight important concepts and issues.", 3, 6, 3, false, false, true, null, "Face-to-face"));

        courses.add(new Course("ACCT3610", "Business Analysis and Valuation","This course is about the analysis of financial information arising primarily from the financial reports of entities. Fundamental analysis techniques are examined in detail with particular emphasis on the application of these techniques in equity (share) valuation decisions. Some attention is also given to credit assessment and debt valuation decisions. The techniques are applied in cases and projects involving listed companies. Topics considered include fundamental ratio analysis using reported and ' off-balance sheet' information,an analysis of accrual accounting and cash flows, the analysis of profitability, growth and valuation generation in a firm, determining the quality of financial reports, forecasting earnings and cash flows, pro-forma analysis for strategy and planning, analysis of risk, and a comparison of alternative valuation models.", 3, 6, 3, true, true, false, null, "Face-to-face"));

        courses.add(new Course("ACCT3625", "Integrated Reporting, Integrated Thinking and Value Creation", "This course is concerned with how organisations create and preserve value over time employing effective business models and a broader range of resources (capitals) than in conventional analyses.  This value creation process is currently being reported upon under the international initiative of Integrated Reporting <IR>, incorporating Integrated Thinking, which is enhancing the way organizations think holistically, plan strategically and report value outcomes.  Integrated Thinking focuses on how executives make business decisions that best utilise all their available resources and relationships (not just financial but including their staff, intellectual property, environmental, and supplier and customer relationships) to implement a strategy for long term value creation. Integrated Reporting then focuses on how they communicate (both internally and to external stakeholders) their unique value creation story, in order to address the question, 'Why should I, or others in society, support this organisation?'  The course is designed to be highly interactive with many illustrations and cases.\n" +
        "\n" +
        "Topics include: The drivers behind the development of the International Framework; creating value over time with Integrated Thinking; and implementation including the design of an internal management system geared to value management rather than traditional financial management.\n" +
        "\n" +
        "Acknowledgement is made of the significant contributions of Integrated Reporting Education Australia and the IIRC in developing and presenting the course.",3, 6, 3, false, false, true, null, "Face-to-face"));

        courses.add(new Course("ACCT3708", "Auditing and Assurance Services",  "This course examines the practice of auditing and the underlying concepts, auditors responsibilities and the audit environment. Although the focus of attention is on audits carried out under the provisions of the Corporations Law, reference is also made to other forms of audit. The course is intended to provide an overview of the audit process as it exists in Australia. Both CIS and computer-assisted audit techniques are an integral part of this course.", 3, 6, 3, true, false, true, "Prerequisite: ACCT2542 or approval from the School", "Face-to-face"));

        courses.add(new Course("FINS1612", "Capital Markets and Institutions", "This course will provide students with an introduction to Australian financial markets and an evaluation of the institutions, instruments and participants involved in the industry. The mainstream markets to be evaluated include the equity, money, bond, futures, options and exchange rate markets. The subject systematically reviews each of the mainstream financial markets and investigates the various institutional participants and the different types of financial instruments offered.", 1, 6, 3, true, true, true, null, "Face-to-face"));

        courses.add(new Course("FINS1613", "Business Finance", "This is a first level corporate finance course that looks at the essential aspects of financial decision-making. The course begins with the different ways in which companies can be structured and the differing types of ownership that exist. Thereafter, the principles and applications of financial mathematics are introduced and used to value securities and investment decisions. Portfolio theory is used to provide a foundation for determining the relationship between expected risk and returns in financial and real asset investments. Dividend payouts and the choices between debt and equity financing, including methods of determining the cost of capital, are also covered. Further, this course includes analysis of the influence of the capital market environment, the implications of financial risk, taxation and the conflict of interest between managers and investors on the value and operation of businesses. The course develops distinct conceptual frameworks and specialised tools for solving real-world financial problems at both the personal and corporate level. Illustrations from real-life corporate practices are used to highlight the importance and relevance of financial management to the realisation of personal and corporate financial objectives. Examples include personal financial planning, funds management, capital raisings, portfolio selection of financial securities, private equity, public floats and the pricing of assets in the stock market.", 1, 6, 3, true, true, true, null, "Face-to-face"));

        courses.add(new Course("FINS2622", "Asia-Pacific Capital Markets", "This course covers essential elements of Asia-Pacific capital markets. Countries include China, Indonesia, Malaysia, South Korea, Thailand, Vietnam, Philippines, Taiwan and others. Areas of interest include interactions of institutions and finance, types of financial markets (equity, debt, derivatives, foreign exchange), corporate governance, globalization, family business models, roles of banks, investment/valuation issues, financing/methods of funds raisings, global portfolio management, financial/currency crises and risk management.", 2, 6, 3, false, true, false, "Prerequisite or co-requisite: FINS1612 and FINS2624", "Face-to-face"));

        courses.add(new Course("FINS2624", "Portfolio Management", "This course will introduce you to investment theories with an equal emphasis on theory and practice. The Markowitz portfolio theory and the CAPM are studied and applied to design portfolios, estimate asset betas, price and manage risk, and identify mis-priced assets. We will also study in detail: bond valuation and associated risks; equity valuation; option valuation and strategies; and evaluation of investment performance where ethical aspects of CFA Institute’s Global Investment Performance Standards (GIPS®) will also be discussed.", 2, 6, 3, true, true, true, null, "Face-to-face"));

        courses.add(new Course("FINS2643", "Wealth Management", "This course teaches a professional financial planning process to manage personal finance, credit, investment and other wealth management tasks. The course consists of four sections: First, an introduction of the financial planning industry, financial planning process and regulatory frameworks. Second, fundamental topics including the taxation, social security, home ownership and credit management. Third, specific topics required for the construction of a comprehensive financial plan: tax planning, investment strategies, risk management and insurance, superannuation, and estate planning. Fourth, the course examines ethics framework and its application in the provision of financial planning advice. The curriculum of this course adapts to professional and regulatory education requirements.", 2, 6, 3, true, false, true, null, "Face-to-face"));

        courses.add(new Course("FINS3616", "International Business Finance", "This course provides students with the basic theoretical and practical knowledge required for the management of financial functions of firms operating in several countries.This includes necessary theory and evidence basic to an understanding of international capital and foreign exchange markets. In particular, this course covers topics such as international diversification, foreign direct investment decisions, cost of capital for multinational corporations, financial and political risks, the role of multinational banks and the financial benefits of Euro-currencies and Eurobonds, short-term financing, and international equity markets. The general emphasis is on the identification and management of risk relating to exchange rate fluctuations and government policy changes.", 3, 6, 3, true, false, true, null, "Face-to-face"));

        courses.add(new Course("FINS3623", "Venture Capital", "This course examines venture capital and private equity investments. In particular, it focuses on issues surrounding the funding of entrepreneurial firms that are financed by venture capital or private equity funds. The course departs from conventional investment approaches that examine risk and return of publicly listed securities, which have previously been covered by your earlier finance courses and analyses issues associated with financing growing, innovation intensive private businesses.", 3, 6, 3, true, false, true, null, "Face-to-face"));

        courses.add(new Course("FINS3625", "Applied Corporate Finance", "This course focuses on practical applications related to financial decision making. Case studies, empirical evidences and current events are used to illustrate the process of making financial decisions commonly faced by corporate managers, investment bankers, investors and regulators. Topics discussed include: advanced issues in corporate valuation and capital budgeting; raising capital; valuation and analysis of real options; leverage choice, mergers and acquisitions and the market for corporate control and governance; and other advanced topics in Corporate Finance.  The course also aims to help students develop oral and writing skills through group assignments and case studies.", 3, 6, 3.5, true, true, true, null, "Face-to-face"));

        courses.add(new Course("FINS3630", "Bank Financial Management", "The theory and practice of banking from a financial management perspective; banks and the financial services industry; regulatory restrictions and financial management; asset management - liquidity and loan management; liability and deposit management; capital structure and dividend decisions; and financial management implications of electronic banking, and other developments are studied.", 3, 6, 3, true, true, true, null, "Face-to-face"));

        courses.add(new Course("FINS3631", "Risk and Insurance", "This course provides a conceptual framework for understanding the effect of risks in personal financial planning and the role of insurance contracts in managing the risks. Specifically, the course introduces the economic principles of risk management and insurance, the essential details about insurance contracts, and the institutional features of Australian insurance markets. It is part of the curriculum at UNSW to meeting professional education requirement of personal financial adviser in Australia.", 3, 6, 3, false, false, true, null, "Face-to-face"));

        courses.add(new Course("FINS3633", "Real Estate Finance", "This course exposes students to concepts, theories and industry practice in real estate finance which is one of the largest and most important components of the financial system. It also introduces valuation and appraisal methods used for real estate finance and investment decision making. The primary goal of this course is to help students acquire the knowledge and develop the analytical skills of real estate finance, including the institutions and instruments used to finance residential and commercial real estate. It is of particular use to students who are interested in working the real estate development, brokerage, mortgage banking and investment banking industries. The main topics covered in the course are mortgage products, mortgage banking, secondary mortgage market and mortgage-backed securities (MBS), financial leverage and commercial real estate finance.", 3, 6, 3, true, false, false, null, "Face-to-face"));

        courses.add(new Course("FINS3635", "Options, Futures and Risk Management", "An intermediate course on options, futures and techniques for managing asset risk. Topics covered include an overview of derivative securities, forward and futures contracts (on stock indices, investment and consumptive assets), options (on stocks, stock indices and futures), hedging positions in options and other derivative securities, binomial option pricing, risk-neutral valuation, the stochastic process followed by stocks, numerical techniques in option pricing, options on non-traded assets, exotic options and pricing biases.", 3, 6, 4, true, true, false, null, "Face-to-face"));

        courses.add(new Course("FINS3636", "Interest Rate Risk Management", "Looks at interest rate risk (IRR) and techniques for managing risk. Topics covered include term structure dynamics (including bond price lattices, spot and forward rate models), analytical and numerical techniques, duration measures, interest rate derivative securities (including options, futures, caps, floors and swaps), mortgage-backed securities and their derivatives, portfolio management, value-at-risk, and the interaction between IRR and credit risk. In discussing interest-rate derivatives, the primary emphasis is on the Hull-White model, but other models, such as the models of Ho-Lee, Cos-Ingersoll-Ross and Heath-Jarrow-Morton are discussed.", 3, 6, 4, false, false, true, null, "Face-to-face"));

        courses.add(new Course("FINS3637", "Wealth Management Advice", "This is a capstone course in the financial planning curriculum to provide students with a practical understanding of the provision of financial product advice and managing clients’ relationships. It consolidates and completes student knowledge and skills required for pursuing employment in the financial planning industry. The course a study of important aspects of ethics, professional standards and Chapter 7 of the Corporation Act to the standards set by the Financial Adviser Standards and Ethics Authority. The course also covers the different elements of financial planning advice including understanding the client's situation and needs, conducting analysis and research, formulating appropriate financial planning strategies, choosing suitable products, preparing a fully compliant financial plan, implementing the financial plan and providing ongoing review and services to the client. The course also covers the knowledge and skills required for providing personal life insurance and general insurance advice. It is a required course for professional recognition in financial planning.", 3, 6, 3, true, true, false,  null, "Face-to-face"));
        courses.add(new Course("FINS3639", "Estate Planning and Asset Protection", "This course provides students with key estate planning knowledge and skills to provide clients a holistic financial and estate planning service. The course deal with the practical application of how an adviser deals with other professionals including lawyers, accountants, tax advisers, etc. to help manage the clients’ estate planning needs, including issues related to succession planning and asset protection. The course consists of a theoretical element and a practical case study element addressing issues facing clients and practitioners in the advice space.", 3, 6, 3, false, true, false, null, "Face-to-face"));
        courses.add(new Course("FINS3640", "Investment Management Modeling", "The course covers complementary topics in investments and funds management. It focuses on 1) equity valuation; 2) alternative investment classes; and 3) portfolio performance measurement and management.\n" +
        "\n" +
        "The equity valuation part covers the main methods of security analysis based on discounted cash flows. The second part covers investments in asset classes other than bonds and currencies. These include real estate, private equity, commodities, currencies, and hedge fund strategies. The final part focuses on issues of performance measurement for active investors and optimal portfolio management. This includes optimal combination of active with passive investment.", 3, 6, 3, true, false, false, null, "Face-to-face"));
        courses.add(new Course("FINS3641", "Security Analysis and Valuation", "This course explores techniques, models and industry practices in equity analysis and valuation. Both quantitative and fundamental analyses are covered to illustrate the work and research behind the trade recommendation reports prepared by the financial analysts.", 3, 6, 3.5, false, true, true, null, "Face-to-face"));
        courses.add(new Course("FINS3648", "Banking, Finance and Technology", "This course deals with implications of technological advances on current and future state of financial industry. The intention is to trigger a disruptive and innovative thinking process and to enforce the notion that recent structural changes across the financial industry provide spectrum of valuable internal and external opportunities. It introduces computational finance and banking technology using the open source programming language of python in the context of finance theory and applications. Case studies to be explored include digital currency (Bitcoin), settlements (Blockchain), hedging, trading and financial advisory.", 3, 6, 3, false, true, true, null, "Face-to-face"));
        courses.add(new Course("FINS3650", "International Banking", "The course examines why risk, return and capital of international banking institutions need to be managed in an integrated manner.  The role of prudential regulation in managing critical risks of internationally active banks is examined in the context of financial crises.  Topics covered also include management of country risk, international trade financing, structured products, project financing structures and economic capital management.", 3, 6, 3, true, true, true, null, "Face-to-face"));
        courses.add(new Course("FINS3655", "Behavioural Finance", "In this course, we will examine how people make predictable and repeatable mistakes in financial decision-making. We will describe the nature of these mistakes and their origin, using insights from psychology, neurosciences and experimental economics on how the human mind works. We will consider how understanding the functioning of the human mind allows us to design a better world—in particular, better stock markets, retirement and healthcare systems. As such, this course is markedly multidisciplinary, lying at the intersection of financial economics and cognitive sciences, with both experimental and theoretical components.", 3, 6, 3, true, false, true, null, "Face-to-face"));
        courses.add(new Course("FINS3666", "Trading and Market Making", "This course introduces undergraduate students to the theory and practice of securities trading at exchanges and dealer markets. It examines existing market structures, types of traders and the strategies they use to achieve their objectives. In this course, we study how and why investors trade and the impact of various market structures on the interaction and outcomes of security transactions. Most finance courses assume that securities trade in an idealized costless, frictionless world. In reality, there are many frictions: bid-ask spreads, trade impact on price, brokerage commissions, quantity limitations, time delays, etc. This subject examines how trading and the design of markets affect volatility, liquidity, trading costs, price efficiency and trading outcomes. The course will also introduce the students to the daily activities of a real trading room. The students are introduced to different markets and through the use of class exercises and in-class trading simulations, the students will be exposed to the practical issues related to trading in financial securities.", 3, 6, 3, true, false, true, null," Face-to-face"));
        courses.add(new Course("FINS3775", "Research Methods in Finance 1","This course prepares students to undertake their own original research at the honours, masters, or doctoral levels. Research Methods in Finance 1 emphasises tools and techniques that constitute the workhorse models in Finance. Students learn a framework to formulate, implement, and interpret econometric specifications and results. The theoretical basis for and application of linear econometric models is covered in detail. Models analysed include ordinary least squares, instrumental variables through two-stage least squares, panel data, and difference-in-differences. Students are also introduced to data management tools and econometric software packages. ",3,6,4,false,false,true,"Prerequisite: 70% or greater in FINS2624 and ECON1203", "Face-to-face"));

        return courses;
    }

    public static ArrayList<Program> getPrograms(){
        ArrayList<Program> programs = new ArrayList<>();
        programs.add(new Program("3979", "Information Systems", "The Bachelor of Information Systems (BIS) degree is a highly prized qualification which provides students with information systems expertise and business skills. The program is intended to develop conceptual and practical skills. After an introductory first stage, students will learn about business systems analysis and design, data management, enterprise systems, business process management, big data business analytics, business systems infrastructure and security as well as mathematics, management accounting and commercial programming.\n" + "\n" +
                "This three year degree is designed for students interested in the use and application of IS and IT commercial environment. It combines courses that assist students to learn about the technical environment of IS as well as develop an understanding of the business implications of these systems. Organisations are always looking for 'business savvy' IS graduates who understand the business and technical issues which surround and impact their information systems.\n" + "\n" +
                "BIS graduates from this degree can target careers in areas such as: business systems analysis, information system development, communications networks analysis and development; IS security development; e-business systems development; business intelligence systems construction, business analytics and IS and IT architecture and infrastructure development and maintenance. The program includes courses from many disciplines including: Information Systems, Technology and Management, and other Commerce and Economics courses.", 144,3));
        programs.add(new Program("3964","Information Systems (Co-op) (Honours)","The BIS (Co-op) (Hons) is a full-time four year Honours degree program. It is an industry linked education program leading to the award of the qualification Bachelor of Information Systems (Co-op) (Honours). The program draws on both Information Systems and business and is intended to develop conceptual and practical skills. After an introductory first stage, students will learn about business analysis systems and design, data management, business systems infrastructure and security as well as commercial programming statistics, management accounting and commercial programming.\n" + "\n" +
                "The BIS (Co-op) (Hons) program has been designed in conjunction with Information Systems and Information Technology industry professionals to provide for the needs of Australian businesses. The program combines the requirements for the award of the degree with 18 months of coordinated industrial experience at three different sponsoring organisations (24 weeks at each). Industry Training extends outside university semesters. \n" + "\n" +
                "The program combines courses that assist students to learn about the technical environment of IS as well as develop an understanding of the business implications of these systems. Organisations are always looking for business savvy IS graduates who understand the business and technical issues which surround and impact their information systems. IS graduates from this degree can target careers in areas such as: business systems analysis, information system development, communications networks analysis and development; IS security development; e-business systems development; business intelligence systems construction, and IS and IT architecture and infrastructure development and maintenance.",
                192,4));
        programs.add(new Program("3584","Commerce / Information Systems","This 4 year dual program leads to the award of a Bachelor of Commerce/Bachelor of Information Systems (BCom/BIS) and will meet the needs of students who want a strong, focused and highly regarded business degree combined with an Information Systems degree. Organisations are always looking for \"business savvy\"? IS graduates who understand the business and technical issues which surround and impact their information systems. As part of the degree program students will complete a major stream in both Information Systems (IS) and an approved disciplinary stream within the UNSW Business School.\n" + "\n" +
                "In selecting their combination of majors, students should note that while there is a wide range of choice, not every combination may be able to be completed in 4 years of full-time study. Students are also not able to take a modern language as their major.",144,3));
        return programs;
    }

    public static ArrayList<Prereq> getPrereqs(){
        ArrayList<Prereq> prereqs = new ArrayList<>();

        prereqs.add(new Prereq("INFS2101","INFS1609"));
        prereqs.add(new Prereq("INFS2101","INFS2603"));
        prereqs.add(new Prereq("INFS2603","INFS1602"));
        prereqs.add(new Prereq("INFS2603","INFS1603"));
        prereqs.add(new Prereq("INFS2605","INFS1603"));
        prereqs.add(new Prereq("INFS2605","INFS1609"));
        prereqs.add(new Prereq("INFS2608","INFS1603"));
        prereqs.add(new Prereq("INFS2621","INFS1602"));
        prereqs.add(new Prereq("INFS2631","INFS1602"));
        prereqs.add(new Prereq("INFS3202","INFS2101"));
        prereqs.add(new Prereq("INFS3303","INFS3202"));
        prereqs.add(new Prereq("INFS3603","INFS1602"));
        prereqs.add(new Prereq("INFS3604","INFS2603"));
        prereqs.add(new Prereq("INFS3605","INFS3634"));
        prereqs.add(new Prereq("INFS3617","INFS1602"));
        prereqs.add(new Prereq("INFS3632","INFS1602"));
        prereqs.add(new Prereq("INFS3634","INFS2605"));
        prereqs.add(new Prereq("INFS3634","INFS2608"));
        prereqs.add(new Prereq("INFS3830","INFS3603"));
        prereqs.add(new Prereq("INFS3873","INFS3603"));
        prereqs.add(new Prereq("ACCT1511","ACCT1501"));
        prereqs.add(new Prereq("INFS4887","INFS4886"));
        prereqs.add(new Prereq("ACCT2507","ACCT1511"));
        prereqs.add(new Prereq("ACCT2522","ACCT1511"));
        prereqs.add(new Prereq("ACCT2542","ACCT1511"));
        prereqs.add(new Prereq("ACCT3563","ACCT2542"));
        prereqs.add(new Prereq("ACCT3583","ACCT2522"));
        prereqs.add(new Prereq("ACCT3601","ACCT2542"));
        prereqs.add(new Prereq("ACCT3610","ACCT2542"));
        prereqs.add(new Prereq("ACCT3610","FINS1613"));
        prereqs.add(new Prereq("ACCT3708","ACCT2542"));
        prereqs.add(new Prereq("FINS2622","FINS1613"));
        prereqs.add(new Prereq("FINS2622","FINS2624"));
        prereqs.add(new Prereq("FINS2624","FINS1613"));
        prereqs.add(new Prereq("FINS2643","FINS2624"));
        prereqs.add(new Prereq("FINS3616","FINS2624"));
        prereqs.add(new Prereq("FINS3623","FINS1613"));
        prereqs.add(new Prereq("FINS3625","FINS1613"));
        prereqs.add(new Prereq("FINS3630","FINS1612"));
        prereqs.add(new Prereq("FINS3630","FINS1613"));
        prereqs.add(new Prereq("FINS3631","FINS1613"));
        prereqs.add(new Prereq("FINS3633","FINS2624"));
        prereqs.add(new Prereq("FINS3635","FINS2624"));
        prereqs.add(new Prereq("FINS3636","FINS2624"));
        prereqs.add(new Prereq("FINS3637","FINS2643"));
        prereqs.add(new Prereq("FINS3639","FINS2624"));
        prereqs.add(new Prereq("FINS3639","FINS2643"));
        prereqs.add(new Prereq("FINS3640","FINS2624"));
        prereqs.add(new Prereq("FINS3641","FINS2624"));
        prereqs.add(new Prereq("FINS3648","FINS1613"));
        prereqs.add(new Prereq("FINS3648","FINS2624"));
        prereqs.add(new Prereq("FINS3650","FINS2624"));
        prereqs.add(new Prereq("FINS3655","FINS1613"));
        prereqs.add(new Prereq("FINS3666","FINS2624"));
        prereqs.add(new Prereq("FINS3775","ECON1203"));
        prereqs.add(new Prereq("FINS3775","FINS2624"));

        return prereqs;
    }

    public static ArrayList<Stream> getStreams() {
        ArrayList<Stream> streams = new ArrayList<>();
        streams.add(new Stream("INFS1C", "Stage 1 Compulsory Core",30,false, "3979"));
        streams.add(new Stream("INFS1CA","Stage 1 Compulsory Option 1", 6, false,"3979"));
        streams.add(new Stream("INFS1CB", "Stage 1 Compulsory Option 2", 6, false,"3979"));
        streams.add(new Stream("INFS2C","Stage 2 Compulsory Core",24,false,"3979"));
        streams.add(new Stream("39793C","Stage 3 Compulsory Core",30,false,"3979"));
        streams.add(new Stream("3979E","INFS Stage 2/3 Electives (choose 2)", 12, false,"3979"));
        streams.add(new Stream("3979F","Free Electives",24,false,"3979"));
        streams.add(new Stream("GENED","General Education",12,false,"3979"));
        streams.add(new Stream("INFS1C", "Stage 1 Compulsory Core",30,false, "3964"));
        streams.add(new Stream("INFS1CA","Stage 1 Compulsory Option 1", 6, false,"3964"));
        streams.add(new Stream("INFS1CB", "Stage 1 Compulsory Option 2", 6, false,"3964"));
        streams.add(new Stream("INFS2C","Stage 2 Compulsory Core",24,false,"3964"));
        streams.add(new Stream("3964C","Stage 3 Compulsory Core",24,false,"3964"));
        streams.add(new Stream("3964CE","INFS Level 2/3 Elective",6,false,"3964"));
        streams.add(new Stream("3964I","Industrial Placement", 36, false,"3964"));
        streams.add(new Stream("3964HC", "Honours Core", 36, false,"3964"));
        streams.add(new Stream("3964HE", "Honours Elective", 12, false,"3964"));
        streams.add(new Stream("GENED","General Education",12,false,"3964"));
        streams.add(new Stream("3584COC","Commerce Core",18,false,"3584"));
        streams.add(new Stream("3584COCO","Commerce Core Option",6,false,"3584"));
        streams.add(new Stream("3584F","Flexible Core",18,false,"3584"));
        streams.add(new Stream("3584I1","Stage 1 Compulsory Core",18,false,"3584"));
        streams.add(new Stream("INFS2C","Stage 2 Compulsory Core",24,false,"3584"));
        streams.add(new Stream("39793C","Stage 3 Compulsory Core",30,false,"3584"));
        streams.add(new Stream("3584M","Commerce Major",48,true,"3584"));
        streams.add(new Stream("3584BE","Business School Electives",18,false,"3584"));
        streams.add(new Stream("GENED","General Education",12,false,"3584"));

        //insert more streams here
        return streams;
    }

    //going to add program identifier to stream/
    /*public static ArrayList<ProgramStream> getProgramStreams() {
        ArrayList<ProgramStream> programStreams = new ArrayList<>();
        programStreams.add(new ProgramStream("3979","INFS1C"));
        programStreams.add(new ProgramStream("3979","INFS1CA"));
        programStreams.add(new ProgramStream("3979","INFS1CB"));
        programStreams.add(new ProgramStream("3979","INFS2C"));
        programStreams.add(new ProgramStream("3979","39793C"));
        programStreams.add(new ProgramStream("3979","3979E"));
        programStreams.add(new ProgramStream("3979","3979F"));
        programStreams.add(new ProgramStream("3979","GENED"));
        programStreams.add(new)

        //insert more programstreams here
        return programStreams;
    }*/

    public static ArrayList<StreamCourse> getStreamCourse() {
        ArrayList<StreamCourse> streamCourses = new ArrayList<>();
        streamCourses.add(new StreamCourse("INFS1C", "INFS1602", true));
        streamCourses.add(new StreamCourse("INFS1C", "INFS1603", true));
        streamCourses.add(new StreamCourse("INFS1C", "INFS1609", true));
        streamCourses.add(new StreamCourse("INFS1C", "ACCT1501", true));
        streamCourses.add(new StreamCourse("INFS1C", "MGMT1001", true));
        streamCourses.add(new StreamCourse("INFS1CA", "ECON1203", false));
        streamCourses.add(new StreamCourse("INFS1CA", "MATH1041", false));
        streamCourses.add(new StreamCourse("INFS1CB", "ACCT1511", false));
        streamCourses.add(new StreamCourse("INFS1CB", "ECON1101", false));
        streamCourses.add(new StreamCourse("INFS2C", "INFS2603", true));
        streamCourses.add(new StreamCourse("INFS2C", "INFS2605", true));
        streamCourses.add(new StreamCourse("INFS2C", "INFS2608", true));
        streamCourses.add(new StreamCourse("INFS2C", "INFS2621", true));
        streamCourses.add(new StreamCourse("39793C", "INFS3603", true));
        streamCourses.add(new StreamCourse("39793C", "INFS3604", true));
        streamCourses.add(new StreamCourse("39793C", "INFS3605", true));
        streamCourses.add(new StreamCourse("39793C", "INFS3617", true));
        streamCourses.add(new StreamCourse("39793C", "INFS3634", true));
        streamCourses.add(new StreamCourse("3979E", "INFS2631", false));
        streamCourses.add(new StreamCourse("3979E", "INFS3020", false));
        streamCourses.add(new StreamCourse("3979E", "INFS3632", false));
        streamCourses.add(new StreamCourse("3979E", "INFS3830", false));
        streamCourses.add(new StreamCourse("3979E", "INFS3873", false));
        streamCourses.add(new StreamCourse("3964C","INFS3604",true));
        streamCourses.add(new StreamCourse("3964C","INFS3605",true));
        streamCourses.add(new StreamCourse("3964C","INFS3617",true));
        streamCourses.add(new StreamCourse("3964C","INFS3634",true));
        streamCourses.add(new StreamCourse("3964CE","INFS2631",false));
        streamCourses.add(new StreamCourse("3964CE","INFS3020",false));
        streamCourses.add(new StreamCourse("3964CE","INFS3603",false));
        streamCourses.add(new StreamCourse("3964CE","INFS3632",false));
        streamCourses.add(new StreamCourse("3964CE","INFS3830",false));
        streamCourses.add(new StreamCourse("3964CE","INFS3873",false));
        streamCourses.add(new StreamCourse("3964I","INFS2101",true));
        streamCourses.add(new StreamCourse("3964I","INFS3202",true));
        streamCourses.add(new StreamCourse("3964I","INFS3303",true));
        streamCourses.add(new StreamCourse("3964HC","INFS4800",true));
        streamCourses.add(new StreamCourse("3964HC","INFS4801",true));
        streamCourses.add(new StreamCourse("3964HC","INFS4802",true));
        streamCourses.add(new StreamCourse("3964HC","INFS4886",true));
        streamCourses.add(new StreamCourse("3964HE","INFS4831",false));
        streamCourses.add(new StreamCourse("3964HE","INFS4854",false));
        streamCourses.add(new StreamCourse("3964HE","INFS4858",false));
        streamCourses.add(new StreamCourse("3964HE","INFS4907",false));
        streamCourses.add(new StreamCourse("3584COC","ACCT1501",true));
        streamCourses.add(new StreamCourse("3584COC","ECON1101",true));
        streamCourses.add(new StreamCourse("3584COC","MGMT1001",true));
        streamCourses.add(new StreamCourse("3584COCO","ECON1203",false));
        streamCourses.add(new StreamCourse("3584COCO","MATH1041",false));
        streamCourses.add(new StreamCourse("3584F","ACCT1511",false));
        streamCourses.add(new StreamCourse("3584F","COMM1000",false));
        streamCourses.add(new StreamCourse("3584F","ECON1102",false));
        streamCourses.add(new StreamCourse("3584F","FINS1613",false));
        streamCourses.add(new StreamCourse("3584F","MARK1012",false));
        streamCourses.add(new StreamCourse("3584F","MGMT1101",false));
        streamCourses.add(new StreamCourse("3584F","TABL1710",false));
        streamCourses.add(new StreamCourse("3584I1","INFS1602",true));
        streamCourses.add(new StreamCourse("3584I1","INFS1603",true));
        streamCourses.add(new StreamCourse("3584I1","INFS1609",true));






        //insert more stream courses here
        return streamCourses;
    }

}
